# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='Altre informazioni')),
            ],
            options={
                'verbose_name_plural': 'Credits',
                'verbose_name': 'Credit',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Ruolo')),
            ],
            options={
                'verbose_name_plural': 'Ruoli',
                'verbose_name': 'Ruolo',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='roles',
            field=models.ManyToManyField(to='credits.Role', verbose_name='Ruoli'),
        ),
    ]
