# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='roles',
            field=models.ManyToManyField(blank=True, to='credits.Role', verbose_name='Ruoli'),
        ),
    ]
