# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(max_length=255, verbose_name='Mobile ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Audio')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio',
            },
        ),
    ]
