# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio'),
        ),
    ]
