# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20170621_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='mobile/audio/', verbose_name='Audio'),
        ),
    ]
