# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Indirizzo IP')),
                ('port', models.SmallIntegerField(verbose_name='Porta')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Time zone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
            ],
            options={
                'verbose_name_plural': 'Lista server',
                'verbose_name': 'Server',
            },
        ),
    ]
