# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170508_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='city',
        ),
    ]
