# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_remove_server_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='time_zone',
        ),
    ]
