# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_server_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(verbose_name='Porta'),
        ),
    ]
