# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20170517_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('ip', 'port')]),
        ),
    ]
