# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('participants', models.ManyToManyField(blank=True, related_name='match_participants', to=settings.AUTH_USER_MODEL, verbose_name='Partecipanti')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to=settings.AUTH_USER_MODEL, verbose_name='Vincitore')),
            ],
            options={
                'verbose_name_plural': 'Match',
                'verbose_name': 'Match',
            },
        ),
    ]
