# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20170517_0907'),
        ('match', '0002_remove_match_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='match',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
    ]
