# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20170607_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.Server', verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to=settings.AUTH_USER_MODEL, verbose_name='Vincitore'),
        ),
    ]
