# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20170612_1036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0004_auto_20170616_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.BooleanField(default=True, verbose_name='Lobby')),
                ('participants', models.ManyToManyField(blank=True, related_name='room_participants', to=settings.AUTH_USER_MODEL, verbose_name='Partecipanti')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.Server', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Stanza',
                'verbose_name_plural': 'Stanze',
            },
        ),
    ]
