# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_img',
            field=models.ImageField(blank=True, null=True, upload_to='match/winner-images/', verbose_name='Immagine'),
        ),
    ]
