# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True, verbose_name='Nickname')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('photo', models.ImageField(upload_to='players/photo/', verbose_name='Foto')),
                ('audio', models.FileField(upload_to='players/audio/', verbose_name='Audio')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tagline')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data di registrazione')),
            ],
            options={
                'verbose_name_plural': 'Players',
                'verbose_name': 'Player',
            },
        ),
    ]
