# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='players/photos/', verbose_name='Foto'),
        ),
    ]
