# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20170327_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default=' ', max_length=128, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
