# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(max_length=36, verbose_name='Token'),
        ),
    ]
