# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20170331_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP'),
        ),
        migrations.AddField(
            model_name='player',
            name='port',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porta'),
        ),
    ]
