# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20170503_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
    ]
