# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20170512_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Porta'),
        ),
    ]
