# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20170512_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDefaultImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('image', models.ImageField(upload_to='players/default-images/', verbose_name='Immagine')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
            ],
            options={
                'verbose_name': 'Immagini di default',
                'verbose_name_plural': 'Immagini di default',
            },
        ),
    ]
